
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Conversion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Conversion", targetNamespace = "http://ws.example.org/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "ConversionResponse", targetNamespace = "http://ws.example.org/", className = "proxy.ConversionResponse")
    @Action(input = "http://ws.example.org/BanqueService/ConversionRequest", output = "http://ws.example.org/BanqueService/ConversionResponse")
    public double conversion(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCompte", targetNamespace = "http://ws.example.org/", className = "proxy.ListCompte")
    @ResponseWrapper(localName = "listCompteResponse", targetNamespace = "http://ws.example.org/", className = "proxy.ListCompteResponse")
    @Action(input = "http://ws.example.org/BanqueService/listCompteRequest", output = "http://ws.example.org/BanqueService/listCompteResponse")
    public List<Compte> listCompte();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws.example.org/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws.example.org/", className = "proxy.GetCompteResponse")
    @Action(input = "http://ws.example.org/BanqueService/getCompteRequest", output = "http://ws.example.org/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
